### ISSUE TITLE
Tuple not recognized as a valid chex.ArrayTree

### ISSUE THREAD

**Issue by mblondel** [google-deepmind/chex#323]
```python
def print_pytree(pytree: chex.ArrayTree):
  print(pytree)


def main(argv):
  # does not work
  # tree_x = (-1.0, {"k1": 1.0, "k2": (1.0, 1.0)}, 1.0)

  # works
  tree_x = [-1.0, {"k1": 1.0, "k2": (1.0, 1.0)}, 1.0]
  print_pytree(tree_x)
```

**Comment by stompchicken** [comment]
Hi @mblondel. Thanks a lot for raising the issue, it was an interesting one to debug!

It looks like this is an issue with Pytype (which is the type checker I assume you are using since you are a GDMer). Neither of those values ought to resolve to  `chex.ArrayTree` because their values are floats and `ArrayTree` only allows scalar values of type `numpy.number` or `numpy.bool_`. The only reason that the list passes the type checker is because pytype is very permissive with heterogenous lists, whereas it is stricter with tuples.

I admit I don't really know why `chex.ArrayTree` excludes Python scalar types, but it [does so explicitly](https://github.com/google-deepmind/chex/blob/a3f1dd0d9ce50dd1b978835318b08e8988d5e564/chex/_src/pytypes.py#L33) and I assume for a good reason. I'll ask the author of that code when they are back from holiday.


I think I am going to close this issue, if you have no objections.

**Comment by mblondel** [comment]
Thanks for the analysis @stompchicken.

According to JAX's [pytree](https://jax.readthedocs.io/en/latest/pytrees.html) documentation, Python standard types such as float or int can be used to define valid pytrees. Given the name `ArrayTree`, it's fine to constrain trees to use scalar types from numpy but my original problem remains that neither JAX nor Chex seem to provide a fully general definition of valid pytree. Do you think it would be possible to create a new type `chex.Pytree` to cover this use case?

**Comment by stompchicken** [comment]
It's true that `chex.ArrayTree` is not a general type definition of a valid pytree. I'm not really sure such a thing is really possible: almost anything can be passed to a Pytree function.
